# Full credits to Marek Kubica who created this action:
# - https://github.com/tarides/changelog-check-action
# - https://github.com/marketplace/actions/check-changelog-for-changes
name: "Check Changelog for changes"

"on":
  pull_request:
    types: ["opened", "reopened", "edited", "synchronize", "labeled", "unlabeled"]
    branches:
      - "main"

jobs:
  check-changelog:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Check for changes in changelog"
        env:
          BASE_REF: "${{ github.event.pull_request.base.ref }}"
          NO_CHANGELOG_LABEL: "${{ contains(github.event.pull_request.labels.*.name, 'no changelog') }}"
        run: |
          if [ "${NO_CHANGELOG_LABEL}" = "true" ]; then
            # "no changelog" set, so finish successfully
            exit 0
          else
            # a changelog check is required
            # fail if the diff is empty
            ! git diff --exit-code "origin/${BASE_REF}" -- CHANGELOG.md
          fi
